spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kona
    password: kona
    username: kona

  output:
    ansi:
      enabled: always

logging:
  level:
    root: INFO
    kona: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.hbm2ddl.SchemaExport: DEBUG