spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kona
    password: kona
    username: kona

  output:
    ansi:
      enabled: always

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG